/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // All theme colors resolve through CSS custom properties so they can
        // flip between dark/light at runtime via the [data-theme] attribute.
        // See src/styles/globals.css :root / [data-theme="light"] blocks.
        void:           'rgb(var(--c-void)            / <alpha-value>)',
        surface:        'rgb(var(--c-surface)         / <alpha-value>)',
        panel:          'rgb(var(--c-panel)           / <alpha-value>)',
        'panel-raised': 'rgb(var(--c-panel-raised)    / <alpha-value>)',
        border:         'rgb(var(--c-border)          / <alpha-value>)',
        'border-bright':'rgb(var(--c-border-bright)   / <alpha-value>)',
        'border-focus': 'rgb(var(--c-accent)          / <alpha-value>)',
        muted:          'rgb(var(--c-muted)           / <alpha-value>)',
        subtle:         'rgb(var(--c-subtle)          / <alpha-value>)',
        text:           'rgb(var(--c-text)            / <alpha-value>)',
        bright:         'rgb(var(--c-bright)          / <alpha-value>)',
        accent:         'rgb(var(--c-accent)          / <alpha-value>)',
        'accent-light': 'rgb(var(--c-accent-light)    / <alpha-value>)',
        'accent-dim':   'rgb(var(--c-accent-dim)      / <alpha-value>)',
        'accent-muted': 'rgb(var(--c-accent)          / 0.13)',
        'accent-glow':  'rgb(var(--c-accent)          / 0.27)',
        success:        'rgb(var(--c-success)         / <alpha-value>)',
        'success-dim':  'rgb(var(--c-success-dim)     / <alpha-value>)',
        'success-muted':'rgb(var(--c-success)         / 0.1)',
        warning:        'rgb(var(--c-warning)         / <alpha-value>)',
        'warning-muted':'rgb(var(--c-warning)         / 0.1)',
        danger:         'rgb(var(--c-danger)          / <alpha-value>)',
        'danger-dim':   'rgb(var(--c-danger-dim)      / <alpha-value>)',
        'danger-muted': 'rgb(var(--c-danger)          / 0.1)',
        teal:           'rgb(var(--c-teal)            / <alpha-value>)',
        'teal-dim':     'rgb(var(--c-teal-dim)        / <alpha-value>)',
        'teal-muted':   'rgb(var(--c-teal)            / 0.1)',
      },
      fontFamily: {
        sans: ['Inter var', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.65rem',  { lineHeight: '1rem'  }],
        'xs':  ['0.75rem',  { lineHeight: '1.1rem'}],
      },
      letterSpacing: {
        tighter: '-0.03em',
        tight:   '-0.015em',
      },
      boxShadow: {
        'glow-sm':  '0 0  8px rgb(var(--c-accent) / 0.2)',
        'glow':     '0 0 20px rgb(var(--c-accent) / 0.27)',
        'glow-lg':  '0 0 40px rgb(var(--c-accent) / 0.2)',
        'inner-glow':'inset 0 1px 0 var(--c-inner-highlight)',
        'card':     '0 1px 3px var(--c-shadow-1), 0 1px 2px var(--c-shadow-2)',
        'card-hover':'0 4px 16px var(--c-shadow-1), 0 2px 4px var(--c-shadow-2)',
        'elevated': '0 8px 32px var(--c-shadow-3), 0 2px 8px var(--c-shadow-1)',
        'modal':    '0 24px 64px var(--c-shadow-4), 0 8px 24px var(--c-shadow-3)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':  'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'fade-in':       'fadeIn 0.25s ease-out both',
        'fade-in-slow':  'fadeIn 0.5s ease-out both',
        'slide-up':      'slideUp 0.35s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-down':    'slideDown 0.35s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-in-right':'slideInRight 0.35s cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in':      'scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) both',
        'pulse-slow':    'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-dot':     'pulseDot 2s ease-in-out infinite',
        'glow':          'glow 2s ease-in-out infinite alternate',
        'shimmer':       'shimmer 2s linear infinite',
        'spin-slow':     'spin 3s linear infinite',
        'bounce-sm':     'bounceSm 0.6s cubic-bezier(0.36, 0.07, 0.19, 0.97) both',
        'progress-indeterminate': 'progressIndeterminate 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:       { from: { opacity: '0' },                             to: { opacity: '1' } },
        slideUp:      { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown:    { from: { opacity: '0', transform: 'translateY(-10px)'},  to: { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(16px)' },  to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn:      { from: { opacity: '0', transform: 'scale(0.95)' },        to: { opacity: '1', transform: 'scale(1)'    } },
        pulseDot:     { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.5', transform: 'scale(0.85)' } },
        glow:         { from: { boxShadow: '0 0 4px rgb(var(--c-accent) / 0.2)' }, to: { boxShadow: '0 0 24px rgb(var(--c-accent) / 0.4)' } },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition:  '200% 0' },
        },
        bounceSm: {
          '0%,100%': { transform: 'translateY(0)'   },
          '40%':     { transform: 'translateY(-4px)' },
          '60%':     { transform: 'translateY(-2px)' },
        },
        progressIndeterminate: {
          '0%':   { transform: 'translateX(-100%) scaleX(0.5)' },
          '50%':  { transform: 'translateX(0%)    scaleX(0.8)' },
          '100%': { transform: 'translateX(200%)  scaleX(0.5)' },
        },
      },
      transitionTimingFunction: {
        'spring':      'cubic-bezier(0.16, 1, 0.3, 1)',
        'bounce-out':  'cubic-bezier(0.36, 0.07, 0.19, 0.97)',
      },
      backdropBlur: { xs: '2px', '4xl': '72px' },
    },
  },
  plugins: [],
};
